Repository SpiNNakerManchester/SpiNNakerGraphFrontEnd, pull requests merged in 2019-08, with the labels that each got.

#114 Not precisely sure of the point of this line, but it should be max(..)
  spinnaker_graph_front_end/examples/hello_world/hello_world.py
Labels: bug

#115 Clean up the C code
  gfe_integration_tests/test_extra_monitor/src/sdram_writer.c
  gfe_integration_tests/test_rte/src/test_rte_during_run.c
  gfe_integration_tests/test_rte/src/test_rte_start.c
  gfe_integration_tests/test_rte/src/test_run_too_long.c
  spinnaker_graph_front_end/examples/Conways/partitioned_example_a_no_vis_no_buffer/src/conways_cell.c
  spinnaker_graph_front_end/examples/Conways/partitioned_example_b_no_vis_buffer/src/conways_cell.c
  spinnaker_graph_front_end/examples/hello_world/src/hello_world.c
  spinnaker_graph_front_end/examples/template/src/c_template_vertex.c
Labels: enhancement, minor

#116 Reduce the level of confusion in some GFE tests
  gfe_integration_tests/test_extra_monitor/sdram_writer.py
  gfe_integration_tests/test_extra_monitor/test_extra_monitor.py
Labels: bug, minor

#118 5.0.1
  requirements.txt
  setup.py
  spinnaker_graph_front_end/_version.py
Labels: enhancement
