Repository SpiNNakerManchester/SpiNNakerGraphFrontEnd, pull requests merged in 2019-10, with the labels that each got.

#127 fixed incorrect import from collections.abc
  setup.py
Labels: bug

#121 only save time_scale_factor in config object
  Jenkinsfile
  spinnaker_graph_front_end/spinnaker.py
Labels: enhancement

#124 Constant
  gfe_integration_tests/test_extra_monitor/sdram_writer.py
  spinnaker_graph_front_end/examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_basic_cell.py
  spinnaker_graph_front_end/examples/Conways/partitioned_example_b_no_vis_buffer/conways_basic_cell.py
  spinnaker_graph_front_end/examples/template/template_vertex.py
Labels: enhancement, minor
