Repository SpiNNakerManchester/SpiNNakerGraphFrontEnd, pull requests merged in 2020-12, with the labels that each got.

#161 Version binding for numpy
  doc/source/conf.py
  requirements.txt
Labels: BLOCKER!, bug

#163 Don't install scipy directly
  Jenkinsfile
Labels: BLOCKER!, bug

#159 removed unused io functionality
  Jenkinsfile
  README.md
Labels: enhancement

#168 Convert to use new actions
  .github/workflows/c_actions.yml
  .github/workflows/python_actions.yml
  .pylintrc
  .travis.yml
Labels: enhancement, minor
