Repository SpiNNakerManchester/SpiNNakerGraphFrontEnd, pull requests merged in 2021-02, with the labels that each got.

#162 More efficient struct handling
  gfe_integration_tests/test_extra_monitor/test_extra_monitor.py
  spinnaker_graph_front_end/examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_basic_cell.py
  spinnaker_graph_front_end/examples/Conways/partitioned_example_b_no_vis_buffer/conways_basic_cell.py
Labels: enhancement, minor

#170 Remove Python 2.7 support
  .github/workflows/python_actions.yml
  doc/doc_requirements.txt
  doc/source/conf.py
  doc/source/index.rst
  gfe_integration_tests/sdram_edge_tests/common/sdram_machine_vertex.py
  gfe_integration_tests/sdram_edge_tests/common/sdram_splitter_external.py
  gfe_integration_tests/sdram_edge_tests/common/sdram_splitter_internal.py
  gfe_integration_tests/sdram_edge_tests/test_c_sdram_with_recording/sdram_machine_recorded_vertex.py
  gfe_integration_tests/sdram_edge_tests/test_c_sdram_with_recording/sdram_splitter_external.py
  gfe_integration_tests/sdram_edge_tests/test_multi_dest_internal/sdram_splitter.py
  gfe_integration_tests/sdram_edge_tests/test_multi_src_external/sdram_splitter.py
  gfe_integration_tests/sdram_edge_tests/test_multi_src_internal/sdram_splitter.py
  gfe_integration_tests/test_extra_monitor/sdram_writer.py
  gfe_integration_tests/test_rte/run_vertex.py
  requirements-test.txt
  requirements.txt
  setup.py
  spinnaker_graph_front_end/examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_basic_cell.py
  spinnaker_graph_front_end/examples/Conways/partitioned_example_b_no_vis_buffer/conways_basic_cell.py
  spinnaker_graph_front_end/examples/hello_world/hello_world_vertex.py
  spinnaker_graph_front_end/examples/hello_world_untimed/hello_world_vertex.py
  spinnaker_graph_front_end/examples/template/template_vertex.py
  spinnaker_graph_front_end/spinnaker.py
  spinnaker_graph_front_end/utilities/simulator_vertex.py
Labels: BLOCKER!, bug

#171 Test 3 9
  .github/workflows/c_actions.yml
  .github/workflows/python_actions.yml
  Jenkinsfile
  doc/source/conf.py
  setup.py
Labels: enhancement, minor

#174 More exposed via global variables
  spinnaker_graph_front_end/spinnaker.py
Labels: enhancement

#176 Test base2
  gfe_integration_tests/script_builder.py
  gfe_integration_tests/sdram_edge_tests/test_c_sdram_with_recording/test_sdram_recording.py
  gfe_integration_tests/sdram_edge_tests/test_constant_external/test_sdram_constant_edges.py
  gfe_integration_tests/sdram_edge_tests/test_constant_internal/test_sdram_internal_edges.py
  gfe_integration_tests/sdram_edge_tests/test_constant_sdram_limited_sdram/test_sdram_internal_edges_low_sdram.py
  gfe_integration_tests/sdram_edge_tests/test_constant_sdram_too_little_sdram/test_sdram_edges_not_enough_sdram.py
  gfe_integration_tests/sdram_edge_tests/test_multi_dest_external/test_sdram_multiple_dests_edges.py
  gfe_integration_tests/sdram_edge_tests/test_multi_dest_internal/test_sdram_internal_edges.py
  gfe_integration_tests/sdram_edge_tests/test_multi_src_external/test_sdram_external_edges.py
  gfe_integration_tests/sdram_edge_tests/test_multi_src_internal/test_sdram_internal_edges.py
  gfe_integration_tests/test_conway_examples.py
  gfe_integration_tests/test_extra_monitor/test_extra_monitor.py
  gfe_integration_tests/test_hello_world.py
  gfe_integration_tests/test_hello_world_untimed.py
  gfe_integration_tests/test_scripts.py
Labels: enhancement
