Repository SpiNNakerManchester/SpiNNakerGraphFrontEnd, pull requests merged in 2021-03, with the labels that each got.

#178 Move examples
  .github/workflows/c_actions.yml
  .github/workflows/python_actions.yml
  doc/source/conf.py
  gfe_examples/Conways/Makefile
  gfe_examples/Conways/__init__.py
  gfe_examples/Conways/no_edges_examples/__init__.py
  gfe_examples/Conways/no_edges_examples/conways_basic_cell.py
  gfe_examples/Conways/no_edges_examples/conways_no_edges.py
  gfe_examples/Conways/one_no_graph_example/__init__.py
  gfe_examples/Conways/one_no_graph_example/conways_no_graph.py
  gfe_examples/Conways/one_no_graph_example/spiNNakerGraphFrontEnd.cfg
  gfe_examples/Conways/partitioned_example_a_no_vis_no_buffer/Makefile
  gfe_examples/Conways/partitioned_example_a_no_vis_no_buffer/__init__.py
  gfe_examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_basic_cell.py
  gfe_examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_partitioned.py
  gfe_examples/Conways/partitioned_example_a_no_vis_no_buffer/src/conways_cell.c
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/Makefile
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/__init__.py
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/conways_basic_cell.py
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/conways_partitioned.py
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/src/conways_cell.c
  gfe_examples/Makefile
  gfe_examples/__init__.py
  gfe_examples/hello_world/Makefile
  gfe_examples/hello_world/__init__.py
  gfe_examples/hello_world/hello_world.py
  gfe_examples/hello_world/hello_world.ybug
  gfe_examples/hello_world/hello_world_vertex.py
  gfe_examples/hello_world/src/hello_world.c
  gfe_examples/hello_world_untimed/Makefile
  gfe_examples/hello_world_untimed/__init__.py
  gfe_examples/hello_world_untimed/hello_world.py
  gfe_examples/hello_world_untimed/hello_world.ybug
  gfe_examples/hello_world_untimed/hello_world_vertex.py
  gfe_examples/hello_world_untimed/src/hello_world.c
  gfe_examples/template/Makefile
  gfe_examples/template/__init__.py
  gfe_examples/template/python_template.py
  gfe_examples/template/src/c_template_vertex.c
  gfe_examples/template/template_vertex.py
  gfe_integration_tests/script_builder.py
  gfe_integration_tests/test_hello_world.py
  gfe_integration_tests/test_hello_world_untimed.py
  gfe_integration_tests/test_scripts.py
  setup.py
  unittests/test_import_all.py
  unittests/test_version.py
Labels: enhancement, minor

#179 Config2
  spinnaker_graph_front_end/spinnaker.py
Labels: enhancement

#177 Split out the list of files to put in documentation
  doc/source/conf.py
  doc/unfiltered-files.txt
Labels: enhancement, minor

#180 Remove a bad link
  doc/source/index.rst
Labels: bug, minor

#183 Improve the GFE API
  gfe_examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_basic_cell.py
  gfe_examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_partitioned.py
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/conways_basic_cell.py
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/conways_partitioned.py
  gfe_examples/hello_world/hello_world.py
  gfe_examples/hello_world/hello_world_vertex.py
  gfe_examples/hello_world_untimed/hello_world.py
  gfe_examples/hello_world_untimed/hello_world_vertex.py
  gfe_examples/template/python_template.py
  gfe_examples/template/template_vertex.py
  gfe_integration_tests/sdram_edge_tests/common/sdram_machine_vertex.py
  gfe_integration_tests/sdram_edge_tests/test_c_sdram_with_recording/sdram_machine_recorded_vertex.py
  gfe_integration_tests/test_extra_monitor/sdram_writer.py
  spinnaker_graph_front_end/utilities/simulator_vertex.py
Labels: enhancement

#181 Better doc
  spinnaker_graph_front_end/__init__.py
  spinnaker_graph_front_end/spinnaker.py
  spinnaker_graph_front_end/utilities/data_utils.py
  spinnaker_graph_front_end/utilities/simulator_vertex.py
Labels: enhancement, minor

#184 Fix some silly errors
  gfe_examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_partitioned.py
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/conways_partitioned.py
  gfe_examples/hello_world_untimed/hello_world.py
  gfe_integration_tests/sdram_edge_tests/test_constant_sdram_limited_sdram/__init__.py
  gfe_integration_tests/test_extra_monitor/test_extra_monitor.py
  gfe_integration_tests/test_hello_world.py
  gfe_integration_tests/test_hello_world_untimed.py
  spinnaker_graph_front_end/utilities/simulator_vertex.py
Labels: BLOCKER!, bug

#182 Simplify recording
  gfe_examples/Conways/partitioned_example_b_no_vis_buffer/src/conways_cell.c
  gfe_examples/hello_world/src/hello_world.c
  gfe_examples/hello_world_untimed/src/hello_world.c
  gfe_examples/template/src/c_template_vertex.c
Labels: enhancement

#185 Use the right token for coveralls
  .github/workflows/python_actions.yml
Labels: BLOCKER!, bug, minor
